services:
  vscode:
    container_name: code-server
    image: codercom/code-server:latest
    environment:
      - DOCKER_USER=hadirgax
      # - PASSWORD=supersecretpassword
    volumes:
      - ./code-server/project:/home/coder/project
      - ./code-server/.config:/home/coder/.config
    user: "0:0"
    restart: always
    ports:
      - 127.0.0.1:8443:8080
