services:
  devcon:
    user: devcon
    image: hadirgax/devcontainer-miniconda:latest
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
      - conda-pkgs-cache:/home/devcon/.conda/pkgs
    depends_on:
      - redis
    command: /bin/bash -c "while sleep 1000; do :; done"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M
          # devices:
          #   - driver: nvidia
          #     capabilities: [gpu]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  conda-pkgs-cache:
