name: Build Miniconda Ubuntu Noble Devcontainer Image
on:
  push:
    branches:
      - main
    tags:
      - 'miniconda-v*.*.*'
    paths:
      - 'devcontainer_images/miniconda/Dockerfile'
      - '.github/workflows/miniconda_ci.yml'
  pull_request:
    paths:
      - 'devcontainer_images/miniconda/Dockerfile'
      - '.github/workflows/miniconda_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.4.0
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.9.0
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: hadirgax/devcontainer-miniconda
          tags: |
            type=ref,event=branch

      - name: build miniconda
        uses: docker/build-push-action@v6.14.0
        with:
          context: ./devcontainer_images/miniconda
          builder: ${{ steps.buildx.outputs.name }}
          file: ./devcontainer_images/miniconda/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}