name: Build Python Bookworm Devcontainer Image
on:
  push:
    branches:
      - main
    paths:
      - 'devcontainer_images/src/python/Dockerfile'
      - '.github/workflows/python_ci.yml'
  pull_request:
    paths:
      - 'devcontainer_images/src/python/Dockerfile'
      - '.github/workflows/python_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.2.0
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: hadirgax/devcontainer-python
          tags: |
            type=ref,event=branch

      - name: build python
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./devcontainer_images/src/python
          builder: ${{ steps.buildx.outputs.name }}
          file: ./devcontainer_images/src/python/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}